### PR TITLE
add support for epics and project tags

### PR DESCRIPTION
**Pull request by rafleze**
I hope this updates will be useful.
These changes are needed.
Thank you for this great job.

### CODE REVIEW

**Comment by marchaase** [comment]
any progress on getting this merged in?

**Comment by fmarco** [comment]
@rafleze Thank your for this PR, we'll have a look as soon as possibile!

**Comment by yakky** [comment]
@rafleze @morlandi is there a way we can merge #77 and #66 they both needs the improvements of the other
Let's talk about the way to cooperate to get both merged

**Comment by yakky** [comment]
merged with #66

**Pull request closed without merging**
