### PR TITLE
bugfixes

### LINKED ISSUE #16: assigned_to in add_task doesn't work
calling ``us.add_task("test task 1", project.task_statuses[0].id, assigned_to=25);`` doesn't assign a user. 

image

### LINKED ISSUE #17: update call on task or user story throws exception
If I try to update a user story or task i get a version parameter exception.

``taiga.exceptions.TaigaRestException: {"version": "The version parameter is not valid"}``

### LINKED ISSUE #18: set custom attribute throws exception
setting existing custom attribute throws exception:

``us.set_attribute('35', 'Desktop')``

``taiga.exceptions.TaigaRestException:  Attribute with id 35 doesn't exist``

### PR DESCRIPTION
**Pull request by dionysiusmarquis**
This will add the ability to set existing custom attributes (fixes #18). Adds version to ``allowed_params`` in class ``UserStory `` and ``Task`` (maybe needs in Issue too?) (fixes #17). Forwards ``**attrs`` in ``UserStory`` ``add_task`` (fixes #16 )

### CODE REVIEW

**Comment by astagi** [comment]
hey @dionysiusmarquis thanks for checking! I'll give a deeper look at your PR during the next week (I'm really busy at the moment). In the mean time please take care of tests, Travis is telling that they fail, maybe some assertion are not valid anymore after your changes (and that's ok, changes are needed cause Taiga's API is still in development).

**Comment by dionysiusmarquis** [comment]
Mhm. Maybe Travis failed because I removed the ``TaigaException`` in ``set_attribute``?

**Comment by astagi** [comment]
Checking it @dionysiusmarquis sorry for my late

**Comment by astagi** [comment]
Thanks a lot @dionysiusmarquis please can you open another PR and add yourself to contributors? (https://github.com/nephila/python-taiga/blob/master/AUTHORS.txt)

**Comment by astagi** [comment]
btw yes the problem with test was that TaigaException won't be raised in set_attribute no more... please run ./runtests.sh script before :)

**Comment by dionysiusmarquis** [comment]
Roger that. You just updated the authors.txt right?

**Comment by astagi** [comment]
Oh I forgot to update this issue sorry! yes I found your name and mail in the commits so I updated the AUTHORS.txt by myself :smiley:

**Comment by dionysiusmarquis** [comment]
Haha alright

**Pull request merged**
