### PR TITLE
Membership endpoints

### PR DESCRIPTION
**Pull request by llonchj**

### CODE REVIEW

**Comment by gabeos** [comment]
:+1: I was actually just about to file an enhancement issue for this, but figured i'd search to make sure it wasn't hiding somewhere. 

cheers @llonchj :beer:

**Comment by llonchj** [comment]
cheers @gabeos

**Comment by astagi** [comment]
Hi @llonchj thanks for your PR :) please check the travis build https://travis-ci.org/nephila/python-taiga/jobs/65983983 there are some flake8 errors :)

**Comment by astagi** [comment]
@gabeos are you talking about this https://github.com/taigaio/taiga-back/issues/349#issuecomment-110633464 ?

@llonchj I'm checking your PR tonight but it looks good at a first glance :)

**Comment by llonchj** [comment]
Thanks @astagi

**Pull request merged**
