### PR TITLE
Add support for swimlanes (#162)

### LINKED ISSUE #162: Add support for swimlanes
## Description

Currently, the API has the ability to read data about swimlanes:

```python
    swimlanes = project.swimlanes
    print(swimlanes)
    # [
    #    {'id': 1234, 'name': 'Swimlane 1', 'order': 0, 'project_id': 1234},
    #    {'id': 1235, 'name': 'Swimlane 2', 'order': 1, 'project_id': 1234}
    #    {'id': 1236, 'name': 'Swimlane 3', 'order': 2, 'project_id': 1234}
    # ]
```

But the objects returned have no models.  There also isn't, as far as I can find, a way to create or modify swimlanes.

## Use cases

In general, it can be nice to add new swimlanes programmatically or to update existing ones.  Changing their order might be especially useful.

My specific use case is because (apparently) duplicating a project does not duplicate its swimlanes.  So I need a way to programmatically create a bunch of swimlanes for new projects.

## Proposed solution

Adding `Swimlane` and `Swimlanes` models, similar to the other models, and similar functions for creating/editing them.

Projects would return these instances instead of the raw objects you get currently when you access `project.swimlanes`.

You could also get a `Swimlane` object back from a `UserStory` when calling `us.swimlane` on it.

## Additional information

To be honest, the REST API documentation does not mention swimlanes **anywhere**.  So it might not be supported on their end.

### PR DESCRIPTION
**Pull request by psybers**
# Description

Adds support for swimlanes.  This adds two new models: `SwimLane` and `SwimLanes`.  It updates the API client to support `client.swimlanes.list()` and adds a `project.swimlanes` attribute.  You can add new swimlanes via `project.add_swimlane('name')`.

## References

Fixes #162 

# Checklist

* [X] I have read the [contribution guide](https://python-taiga.readthedocs.io/en/latest/contributing.html)
* [X] Code lint checked via `inv lint`
* [X] ``changes`` file included (see [docs](https://python-taiga.readthedocs.io/en/latest/contributing.html#pull-request-guidelines))
* [X] Usage documentation added in case of new features
* [X] Tests added

### CODE REVIEW

**Review by yakky — APPROVED** [review]

**Comment by yakky** [comment]
awesinem @psybers thanks a lot

**Comment by psybers** [comment]
Wait, I think I forgot one thing: setting the default swimlane on a project.

**Comment by protoroto** [comment]
@psybers I'm not very familiar with swimlanes, so I don't really understand the problems of not setting the default swimlane on a project. Will you open another pr to address this, or should we release a new version without it?

**Comment by psybers** [comment]
I think it is a super small change.  There just needs to be one method in Project to set the default swimlane.  The API calls `/projects/#` with a PATCH and sets a single value, `default_swimlane`.  This was the hack I put in to get it working on my side (without this PR):

```python
def set_default_swimlane(self, id, **attrs):
    attrs.update({"default_swimlane": id})
    response = self.requester.patch("/projects/" + str(self.id), payload=attrs)
    return response.json()
```

I can get another PR in later today.

**Comment by psybers** [comment]
I added PR #167 (referencing issue #166) to fix this issue.

@protoroto Note that it is not a huge problem, if you release without this additional PR they can still read/write/update swimlanes, they just can't set the default.  I'm not sure what Taiga does with no default set, but I suspect the UI would just default to the 'first' (based on order) when adding a new user story.

**Pull request merged**
